# -*- coding: utf-8 -*-
"""codesheet taller 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cFTar94n3U1e5r1881LY58uZlNkPgRYT
"""

import sympy as sp

#ejercicio 3 (1.1.6)
def centroide_triangulo(a, b, c):
    """
    Calcula el centroide de un triángulo dados tres vectores posición.
    a, b, c deben ser vectores columna de SymPy.
    """
    return (a + b + c) / 3

# Definimos los vectores (puedes cambiar estos valores para cualquier caso)
a = sp.Matrix([1, 2, 3])
b = sp.Matrix([4, 5, 6])
c = sp.Matrix([7, 8, 9])

# Calculamos el centroide
g = centroide_triangulo(a, b, c)
print(f"Centroide g = ({g[0]}, {g[1]}, {g[2]})")